Interface fix v2
oaeproject/Cake pull request #3
Opened 2021-03-04 16:28 UTC by RitaOak

2021-03-04 16:34 UTC, brecke requested changes

2021-03-04 16:34 UTC, brecke commented on src/components/oae-sidebar/assets/oae-logo.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 173.25 158.6"><defs><style>.cls-1{fill:#3a72e9;}.cls-2{fill:#78c9ec;}</style></defs><title>logo</title><circle cl
Don't we have this logo already somewhere within the project? I'll need in the global `assets` folder from the `home-nav` component. Maybe it shouldn't be a local asset?

2021-03-04 16:34 UTC, brecke commented on src/components/oae-sidebar/oae-sidebar.tsx
> +  assetsDirs: ['assets'],
same as before, maybe this is not a good candidate for a local asset as we'll need it from other places such as the `home-nav` component (top bar of the homepage)

2021-03-04 17:37 UTC, brecke requested changes

2021-03-04 17:37 UTC, brecke commented on src/components/oae-sidebar/oae-sidebar.tsx
> +  assetsDirs: ['assets'],
can't we remove it?

2021-03-04 17:37 UTC, brecke commented on src/components/oae-sidebar/oae-sidebar.tsx
> +                <img src={getAssetPath(`../assets/logo/${this.image}`)} />
I might be wrong, but... `getAssetPath()` gives us the absolute path which ends in `assets` so no point in going back one `../` and then entering `assets` again. I bet `getAssetPath(`logo/${this.image}`)` works just fine.

2021-03-04 17:37 UTC, brecke commented on src/components/oae-sidebar/oae-sidebar.tsx
> +                  <img class="is-rounded" src={getAssetPath(`../assets/images/${this.avatar}`)} />
same as above

2021-03-04 17:37 UTC, brecke commented on src/components/home-nav/home-nav.tsx
> +              <img src={getAssetPath(`../assets/logo/${this.image}`)} />
I might be wrong, but... `getAssetPath()` gives us the absolute path which ends in `assets` so no point in going back one `../` and then entering `assets` again. I bet `getAssetPath(`logo/${this.image}`)` works just fine.

2021-03-05 12:44 UTC, RitaOak commented on src/components/oae-sidebar/oae-sidebar.tsx
> +                <img src={getAssetPath(`../assets/logo/${this.image}`)} />
Apparently not, because the folder we're accessing is outside of /components/oae-sidebar/, given that the logo and the avatar are now global assets. The following variations didn't work:

- `getAssetPath(`.../logo/${this.image}`)`
- `getAssetPath(`../logo/${this.image}`)`
- `getAssetPath(`./logo/${this.image}`)`
- `getAssetPath(`logo/${this.image}`)`

The specified path needs to point `../assets/logo/${this.image}` for the img to display. At least, this has been the best solution I found so far.

2021-03-05 12:44 UTC, RitaOak commented on src/components/oae-sidebar/oae-sidebar.tsx
> +                  <img class="is-rounded" src={getAssetPath(`../assets/images/${this.avatar}`)} />
Same here

2021-03-05 12:44 UTC, RitaOak commented on src/components/home-nav/home-nav.tsx
> +              <img src={getAssetPath(`../assets/logo/${this.image}`)} />
Same here

2021-03-05 14:51 UTC, brecke requested changes

2021-03-05 14:51 UTC, brecke commented on src/components/oae-sidebar/oae-sidebar.tsx
> +                <img src={getAssetPath(`../assets/logo/${this.image}`)} />
what about `<img src={getAssetPath(`./assets/logo/${this.image}`)} />`? seems to work

2021-03-05 15:23 UTC, brecke approved these changes

2021-03-05 15:24 UTC, merged