Styling of icons and formatting
oaeproject/Cake pull request #51
Opened 2021-05-12 19:51 UTC by RitaOak

2021-05-12 19:52 UTC, RitaOak commented
TODO:

add spacing
center icons
replace icons with better svgs when possible

2021-05-12 20:17 UTC, RitaOak commented
TODO:

Add 'Sign In' section above buttons
Add --------or-------- section after buttons

2021-05-13 08:17 UTC, brecke requested changes

2021-05-13 08:17 UTC, brecke commented on src/components/HomeTopBar.svelte
> +              open
`open`: do we want it to open automatically?

2021-05-13 08:17 UTC, brecke commented on src/helpers/authentication.ts
> +    name: "Sign in with CAS",
there are all "translations" from the json translation files, so don't bother change it here, we'd better change it directly on `en_GB.json` and `fr_FR.json` (need to rebase to get them) and then: `$_('<entry>')`

2021-05-13 13:36 UTC, RitaOak commented on src/components/HomeTopBar.svelte
> +              open
I noticed that this removes the divider line in the modal, which makes the overall design much more appealing. But if you think we should keep it closed by default, then I can change it and try to find another fix for it

2021-05-13 13:39 UTC, RitaOak commented on src/helpers/authentication.ts
> +    name: "Sign in with CAS",
I added these because you only get a "with `authentication method`" in the interface otherwise. I'll change that asap!

2021-05-13 13:52 UTC, brecke commented on src/components/HomeTopBar.svelte
> +              open
we cannot launch the modal right away, it covers the homepage and we don't know whether the user wants to login or not. He might be just visiting.

2021-05-13 13:53 UTC, brecke commented on src/helpers/authentication.ts
> +    name: "Sign in with CAS",
oh, right. Let's try and fix that right away. I hope the translations have that entry already, otherwise let's create them.

2021-05-17 10:44 UTC, brecke requested changes

2021-05-17 10:44 UTC, brecke commented on src/components/HomeTopBar.svelte
> +            <h1 class="modal-title">Sign in with OAE</h1>
Sign in *to* OAE

2021-05-17 10:44 UTC, brecke commented on src/components/HomeTopBar.svelte
> +  const getHeadingForDialog = () => `${$user.tenant.alias}`;
translation missing?

2021-05-17 16:55 UTC, RitaOak commented on src/components/HomeTopBar.svelte
> +  const getHeadingForDialog = () => `${$user.tenant.alias}`;
removing redundancy. For UI purposes, we just need the name of the tenant and give focus to the rest of the modal

2021-05-17 16:56 UTC, RitaOak commented on src/components/HomeTopBar.svelte
> +            <h1 class="modal-title">Sign in with OAE</h1>
corrected!

2021-05-18 13:47 UTC, brecke approved these changes

2021-05-18 13:50 UTC, merged