Main layout topbar
oaeproject/Cake pull request #59
Opened 2021-06-21 15:05 UTC by RitaOak

New topbar for the main layout.

2021-06-29 10:46 UTC, brecke approved these changes
I know this is not final and you meant to have placeholders, but take these comments as reminders for later

2021-06-29 10:46 UTC, brecke commented on src/components/MainTopBar.svelte
> +  const log = anylogger('maintopbar');
if you're not logging anything, then there is no need to import it

2021-06-29 10:46 UTC, brecke commented on src/components/MainTopBar.svelte
> +      <img alt="oae-logo" src={oaeLogo} />
this should be the tenant logo, right? we already have it on the homepage topbar, check it out (no need to add new static things when we have already made them dynamic)

2021-06-29 10:46 UTC, brecke commented on src/components/MainTopBar.svelte
> +              <img class="is-rounded" src={avatar}/>
is this the user avatar? then we also have it dynamic... somewhere.

2021-06-29 10:47 UTC, brecke requested changes
I know this is not final and you meant to have placeholders, but take these comments as reminders for later

2021-07-27 10:18 UTC, brecke requested changes
just minor changes, apart from the aesthetics we've discussed already

2021-07-27 10:18 UTC, brecke commented on src/components/MainTopBar.svelte
> +      const text = await response.text();
let's rename `text` into something more accurate like `logoUrl` or `tenantLogoUrl`.

2021-07-27 10:18 UTC, brecke commented on src/components/MainTopBar.svelte
> +      tenantLogo = logoToDisplay;
we can also remove the variable `logoToDisplay` and instead play with `tenantLogo` alone. Like this:  

```
  let tenantLogo;

  onMount(async () => {
    try {
      const response = await fetch('/api/ui/logo');
      const tenantLogoUrl = await response.text();

      // TODO we need to change the backend to deliver the correct filepath if default
      const isDefaultLogo = pipe(split('/'), init, join('/'), equals(DEFAULT_LOGO))(tenantLogoUrl);

      switch (isDefaultLogo) {
        case true:
          tenantLogo = 'assets/logos/oae-logo.svg';
          break;
        default:
          tenantLogo = tenantLogoUrl;
          break;
      }
    } catch (error) {
      log.error(`Error fetching the tenant logo`, error);
    }
  });
```

2021-07-27 10:18 UTC, brecke commented on src/components/MainTopBar.svelte
> +    <a class="navbar-item" href="https://bulma.io">
unrelated link

2021-07-27 10:18 UTC, brecke commented on src/components/MainTopBar.svelte
> +            <i class="fas fa-filter" />
my suggestion is that we should make this gray as a way to indicate they're not clicable or useful at this point. Like a placeholder that will eventually become a feature.

2021-07-30 11:08 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +  const log = anylogger('maintopbar');
When I remove this instance it gives me an error on line 26

` } catch (error) {
      log.error(`Error fetching the tenant logo`, error);
    }`

So I should leave it because it seems to be directly affecting the tenant logo. What do you think?

2021-07-30 11:22 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +              <img class="is-rounded" src={avatar}/>
Should be fixed now

2021-07-30 11:30 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +  const avatar = '/assets/logos/avatar.jpg';
I'm using a static image for the user avatar but we have the code for a semi-dynamic avatar. Should improve this next week and make it work correctly

2021-07-30 11:31 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +      const text = await response.text();
fixed

2021-07-30 11:32 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +      tenantLogo = logoToDisplay;
fixed

2021-07-30 11:33 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +    <a class="navbar-item" href="https://bulma.io">
fixed, it now points to the dashboard

2021-07-30 11:41 UTC, RitaOak commented on src/components/MainTopBar.svelte
> +            <i class="fas fa-filter" />
Solved

2021-08-02 13:13 UTC, brecke requested changes
A few notes:

- Sidebar is missing some styles
- I've added some fixes in a new commit, check it out

2021-08-02 13:13 UTC, brecke commented on src/components/Sidebar.svelte
> -  <nav class="level sidebar-dropdown">
this is probably why the sidebar now looks different?

2021-08-02 17:31 UTC, RitaOak commented on src/components/Sidebar.svelte
> -  <nav class="level sidebar-dropdown">
Perhaps! Hopefully it's working now.

2021-08-06 13:22 UTC, brecke requested changes
The only thing missing is centering the search bar on the top bar 👌🏻

2021-08-11 15:06 UTC, brecke requested changes
We don't need the `nginx` config files in this repo, let's remove them shall we?

As soon as you remove them, I shall try this locally and test it myself :)

2021-08-12 08:54 UTC, brecke approved these changes
LGTM

2021-08-12 09:57 UTC, merged